---
deployment:
  tasks:
    - |
      if [ ! -f .deploy.conf ]
      then
          cp .deploy.example.conf .deploy.conf
          exit
      else
          source .deploy.conf
      fi

    - export DEPLOY_LOG="$DEPLOY_PATH/.deploy.log"
    - export DEPLOY_LIST="$DEPLOY_PATH/.deployed-files.txt"

    - if [ ! -d "$DEPLOY_PATH" ]; then mkdir -p "$DEPLOY_PATH"; fi

    - echo "=== Deployment started" > "$DEPLOY_LOG"

    # Remove old files and empty directories
    - |
      if [ -f "$DEPLOY_LIST" ]
      then
        echo "=== Removing old files" >> "$DEPLOY_LOG"
        tac "$DEPLOY_LIST" | while read file; do
          if [ -d "$DEPLOY_PATH/$file" ] && [ ! "$(ls -A "$DEPLOY_PATH/$file")" ]
          then
            echo "Removing empty directory: $file" >> "$DEPLOY_LOG"
            rmdir "$DEPLOY_PATH/$file"
          elif [ -f "$DEPLOY_PATH/$file" ]
          then
            echo "Removing file: $file" >> "$DEPLOY_LOG"
            rm "$DEPLOY_PATH/$file"
          fi
        done
      fi

    # Copy new files
    - |
      echo "=== Copying new files" >> "$DEPLOY_LOG"
      find -mindepth 1 \
          ! -path "*/.git*" \
          ! -name ".cpanel.yml" \
          ! -name ".deploy.conf" \
          ! -name ".deploy.example.conf" \
          -exec echo "{}" >> "$DEPLOY_LOG" \;\
          -exec cp -RTpu "{}" "$DEPLOY_PATH/{}" \;\
          -fprint "$DEPLOY_LIST"

    - cd $DEPLOY_PATH

    # Set up Composer
    - php -v &>> "$DEPLOY_LOG"
    - if [ ! -f composer.phar ]; then wget -O - https://getcomposer.org/installer | php &>> "$DEPLOY_LOG"; fi
    - php composer.phar install --no-interaction --ignore-platform-reqs --no-dev &>> "$DEPLOY_LOG"

    # Set up Node.js to the latest LTS version
    - |
      if ! command -v node &> /dev/null; then
        echo "Node.js not found. Installing Node.js..."
        curl -sL https://deb.nodesource.com/setup_lts.x | bash -
        apt-get install -y nodejs
      fi

    # Set up Vue.js/NPM assets
    - |
      if [ -f package.json ]; then
        echo "=== Building Vue.js/NPM assets" >> "$DEPLOY_LOG"
        npm install
        npm run build
      fi

    - php artisan storage:link &>> "$DEPLOY_LOG"

    # Setup dotenv and run migrations
    - |
      if [ ! -f .env ]
      then
        cp .env.example .env
        php artisan key:generate &>> "$DEPLOY_LOG"
      else
        if [[ "$RUN_MIGRATIONS" == "true" ]]; then php artisan migrate --seed &>> "$DEPLOY_LOG"; fi
      fi

    - echo "=== Deployment Complete" >> "$DEPLOY_LOG"
